name: Build My EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install dependencies (From Requirements)
      # سنحاول تثبيت المكتبات، وإذا فشل سنكمل ولن نتوقف
      continue-on-error: true 
      run: |
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build EXE
      # أضفنا --collect-all لمحاولة جمع كل ما يحتاجه الكود تلقائياً
      run: pyinstaller --onefile --noconsole --clean vacations.py
      
    - name: Save Result
      if: success() # لن يتم الرفع إلا إذا نجح البناء
      uses: actions/upload-artifact@v4
      with:
        name: My_Vacations_App
        path: dist/*.exe
